services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
  core:
    build:
      context: .
      dockerfile: apps/core/Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - 4010:4010
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog
      - REDIS_URI=redis://redis:6379
      - PORT=4010
  blog:
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    depends_on:
      - core
    ports:
      - 3001:3001
    environment:
      - API_URL=http://core:4010/api
      - PORT=3001
